version: "3.8"

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - C:\Users\Guilherme Pelzl\Desktop\postgres-logistic\postgres:/var/lib/postgresql/data

volumes:
  pgdata:
    external: false
